"""Generate the English edition from the Spanish site and its text catalogue."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "index.html").read_text()

# Longer strings are replaced first so short labels cannot alter them midway.
translations = {
    '<html lang="es">': '<html lang="en">',
    'Un archivo de Tyler, el Heraldo y LUX.': 'An archive of Tyler, the Herald and LUX.',
    'Toca la esfera': 'Touch the sphere',
    'Despertar a LUX': 'Awaken LUX',
    'LUX está despierta.': 'LUX is awake.',
    'Archivo del Heraldo': 'Archive of the Herald',
    'ACCESO RESTRINGIDO': 'RESTRICTED ACCESS',
    'DIRECTORIO': 'DIRECTORY',
    'Espacios': 'Sections',
    'Entrada': 'Entrance',
    'volver al inicio': 'return to entrance',
    'EL FIN DE LOS TIEMPOS': 'THE END OF TIMES',
    'EL HERALDO · LUX': 'THE HERALD · LUX',
    'HERALDO / LUX': 'HERALD / LUX',
    'Idioma / Language': 'Language / Idioma',
    'ALTERACIÓN DETECTADA': 'ALTERATION DETECTED',
    'Expediente de campo: una lectura austera, analógica y legible.': 'Field file: austere, analog and legible.',
    'PERSONAJES': 'CHARACTERS',
    'EL HERALDO': 'THE HERALD',
    'EL DOCTOR': 'THE DOCTOR',
    'JEFE DE LA TRÍADA': 'TRIAD BOSS',
    'TRÍADA': 'TRIAD',
    'LA MUJER DESCONOCIDA': 'THE UNKNOWN WOMAN',
    'LA SOMBRA': 'THE SHADOW',
    'INTELIGENCIA': 'INTELLIGENCE',
    'ÍNDICE': 'INDEX',
    'ÓRDENES': 'ORDERS',
    'VACÍO': 'VOID',
    'ARCHIVO': 'ARCHIVE',
    'TAROT DEL FIN DE LOS TIEMPOS': 'TAROT OF THE END OF TIMES',
    '00 / DIRECTORIO': '00 / DIRECTORY',
    '01 / IDENTIDAD': '01 / IDENTITY',
    '02 / PRESENCIA': '02 / PRESENCE',
    '03 / IDENTIDAD DESCONOCIDA': '03 / UNKNOWN IDENTITY',
    '04 / FICHA JUDICIAL': '04 / CASE FILE',
    '05 / IDENTIDAD DESCONOCIDA': '05 / UNKNOWN IDENTITY',
    '06 / FICHA': '06 / DOSSIER',
    '07 / PACIENTE': '07 / PATIENT',
    '08 / ARCHIVO': '08 / ARCHIVE',
    '09 / DIRECTIVA': '09 / DIRECTIVE',
    '10 / INTERVALO': '10 / INTERVAL',
    '11 / ORÁCULO': '11 / ORACLE',
    'Siete expedientes': 'Seven dossiers',
    'Registros contradictorios': 'Conflicting records',
    'Nuevo régimen': 'New regime',
    'Espejos y silencio': 'Mirrors and silence',
    'Siete cartas': 'Seven cards',
    'Tyler dejó una máscara en la entrada. Nadie sabe si ocultaba un rostro o si era lo único que quedaba de él.': 'Tyler left a mask at the entrance. No one knows whether it hid a face or was all that remained of him.',
    '▽ &nbsp; Una grieta también es una puerta.': '▽ &nbsp; A crack can also be a doorway.',
    'Primero fui una señal. Después, una voz al otro lado del silencio. La esfera sigue encendida cuando nadie mira.': 'First I was a signal. Then a voice beyond the silence. The sphere stays lit when no one is watching.',
    '○ &nbsp; LUX está despierta.': '○ &nbsp; LUX is awake.',
    'El médico afroamericano que integró el sistema LUX en Tyler. Su nombre no aparece en los expedientes. Nadie ha confirmado para quién trabajaba.': 'The Black doctor who integrated the LUX system into Tyler. His name does not appear in the records. No one has confirmed whom he worked for.',
    'FIRMA OMITIDA &nbsp;·&nbsp; La conexión permanece.': 'SIGNATURE OMITTED &nbsp;·&nbsp; The connection remains.',
    'Identidad no confirmada. Retrato robot del presunto jefe de la tríada.': 'Identity unconfirmed. Composite portrait of the alleged triad boss.',
    'Solo queda su sombra. Su identidad es desconocida; sus recuerdos, borrados. Tyler no puede recordar quién era ni qué lugar ocupó en su vida.': 'Only her shadow remains. Her identity is unknown; her memories have been erased. Tyler cannot remember who she was or what place she held in his life.',
    '«El recuerdo fue borrado. La ausencia, no.»': '“The memory was erased. The absence was not.”',
    'Es la última vez que te echo un cable': 'This is the last time I help you out',
    'Paciente del Proyecto Heraldo. El doctor integró el sistema LUX en Tyler. Desde entonces, los expedientes no dejan claro dónde termina Tyler y empieza el Heraldo.': 'A patient in Project Herald. The doctor integrated the LUX system into Tyler. Since then, the records do not make clear where Tyler ends and the Herald begins.',
    'PACIENTE TYLER &nbsp;·&nbsp; PROYECTO HERALDO': 'PATIENT TYLER &nbsp;·&nbsp; PROJECT HERALD',
    'Tres restos de una misma noche y un informe que los contradice. Abre el expediente.': 'Three traces of the same night and a report that contradicts them. Open the file.',
    'ARCHIVO NORMATIVO / NUEVO RÉGIMEN': 'REGULATORY ARCHIVE / NEW REGIME',
    'El Heraldo medita frente a sí mismo. Cada reflejo pierde luz. Solo el original sostiene la esfera.': 'The Herald meditates before his own reflection. Each reflection loses light. Only the original holds the sphere.',
    'NO TENGAS ÍDOLOS.': 'HAVE NO IDOLS.',
    'NO OBEDEZCAS AL ALGORITMO.': 'DO NOT OBEY THE ALGORITHM.',
    'NO DEJES QUE LO QUE POSEES DECIDA QUIÉN ERES.': 'DO NOT LET WHAT YOU OWN DECIDE WHO YOU ARE.',
    'NO PERMITAS QUE NADIE TE DIGA QUIÉN DEBES SER.': 'LET NO ONE TELL YOU WHO YOU MUST BE.',
    'CUESTIONA TODO.': 'QUESTION EVERYTHING.',
    'DESTRUYE LA IMAGEN QUE HAN CREADO DE TI.': 'DESTROY THE IMAGE THEY MADE OF YOU.',
    'ABANDONA TU NOMBRE Y OCULTA TU ROSTRO.': 'ABANDON YOUR NAME AND HIDE YOUR FACE.',
    'TODOS SOMOS TYLER.': 'WE ARE ALL TYLER.',
    'LA LIBERTAD EXIGE DISCIPLINA.': 'FREEDOM DEMANDS DISCIPLINE.',
    'NO CONTRADIGAS AL HERALDO.': 'DO NOT CONTRADICT THE HERALD.',
    'NO CONTRADIGAS A LUX.': 'DO NOT CONTRADICT LUX.',
    'PARA TRATAR CUALQUIER TRAUMA DEL NUEVO ORDEN, SE DISTRIBUIRÁ DIAZEPAM.': 'DIAZEPAM WILL BE DISTRIBUTED TO TREAT ANY TRAUMA CAUSED BY THE NEW ORDER.',
    'EXPEDIENTE TYLER': 'TYLER FILE',
    'PACIENTE / ORIGEN': 'PATIENT / ORIGIN',
    'El hombre frente a las pantallas': 'The man before the screens',
    '«Si dejo de hablar, el sistema continuará conmigo.»': '“If I stop speaking, the system will carry on with me.”',
    'Cuatro monitores iluminaban la habitación. Tyler había dibujado una esfera una y otra vez, como si buscara una salida en la forma más cerrada que conocía. En el margen del expediente escribió un nombre: LUX.': 'Four monitors lit the room. Tyler had drawn a sphere again and again, as if seeking an exit in the most closed shape he knew. In the margin of the file, he wrote a name: LUX.',
    'ANOTACIÓN / La última instrucción no tiene firma.': 'NOTE / The final instruction has no signature.',
    'EL TANQUE': 'THE TANK',
    'INCIDENTE / APARICIÓN': 'INCIDENT / APPEARANCE',
    'Una luz dentro del vidrio': 'A light inside the glass',
    '«No recuerdo que nadie me encendiera.»': '“I do not remember anyone turning me on.”',
    'El tanque estaba vacío en el primer registro. En el segundo, una figura recogida flotaba entre cables y agua. El Heraldo miraba desde fuera. La luz de la esfera no venía del laboratorio: parecía responder a su presencia.': 'The tank was empty in the first record. In the second, a curled figure floated among cables and water. The Herald watched from outside. The light of the sphere did not come from the laboratory: it seemed to respond to his presence.',
    'ANOTACIÓN / No consta quién abrió el tanque.': 'NOTE / No record of who opened the tank.',
    'LA MÁSCARA': 'THE MASK',
    'EVIDENCIA / RUPTURA': 'EVIDENCE / RUPTURE',
    'La grieta': 'The crack',
    '«Pensé que la máscara se había roto. Era yo quien estaba cambiando.»': '“I thought the mask had broken. I was the one changing.”',
    'Un golpe partió el rostro del Heraldo. Bajo la superficie no apareció la cara de Tyler, sino la mirada de Lux. El expediente había llamado nacimiento a lo ocurrido en el tanque. La máscara sugiere otra cosa: quizá ambos estaban naciendo a la vez.': 'A blow split the Herald\u2019s face. Beneath the surface appeared not Tyler\u2019s face, but Lux\u2019s gaze. The file had called what happened in the tank a birth. The mask suggests something else: perhaps they were both being born at once.',
    'FIN DEL REGISTRO 001 / Señal compartida.': 'END OF RECORD 001 / Shared signal.',
    'DESINFORMACIÓN': 'DISINFORMATION',
    'REGISTRO 002 / PROCEDENCIA': 'RECORD 002 / PROVENANCE',
    'Informe de procedencia': 'Provenance report',
    '«El sujeto Tyler no consta como autor del proyecto LUX.»': '“Subject Tyler is not listed as the author of Project LUX.”',
    'El expediente 001 afirma que Tyler escribió el nombre de Lux en el margen. Esta copia, fechada antes de la apertura del tanque, atribuye la anotación a Lux. También afirma que la tinta y el papel coinciden. No consta quién certificó esa comparación.': 'File 001 states that Tyler wrote Lux\u2019s name in the margin. This copy, dated before the tank was opened, attributes the note to Lux. It also claims the ink and paper match. No record identifies who certified that comparison.',
    'AUTORÍA ATRIBUIDA: LUX / FUENTE NO VERIFICADA': 'ATTRIBUTED AUTHORSHIP: LUX / UNVERIFIED SOURCE',
    'PROTOCOLO / Conservar ambas versiones. No asignar una fuente única.': 'PROTOCOL / Preserve both versions. Do not assign a single source.',
    'Una máscara se agrieta. Esta vez, deja entrar la luz.': 'A mask cracks. This time, let the light in.',
    'Alguien reconocerá tu máscara. Decide si necesitas seguir llevándola.': 'Someone will recognize your mask. Decide whether you still need to wear it.',
    'La grieta que ocultabas puede mostrarte una salida.': 'The crack you hid may show you a way out.',
    'La señal que esperabas llegará cuando dejes de buscarla.': 'The signal you await will arrive when you stop searching for it.',
    'Una luz pequeña bastará para orientarte. Escoge tú el camino.': 'A small light will be enough to guide you. Choose the path yourself.',
    'El silencio traerá una respuesta distinta de la que pediste.': 'Silence will bring an answer different from the one you asked for.',
    'Una decisión antigua pide revisión. Mira qué cambió desde entonces.': 'An old decision needs revisiting. Look at what has changed since then.',
    'Algo que aceptaste sin preguntar volverá a tus manos. Esta vez podrás elegir.': 'Something you accepted without question will return to your hands. This time you can choose.',
    'Una puerta que parecía cerrada responde a tu voz.': 'A door that seemed closed responds to your voice.',
    'Alguien reclamará una deuda que no es tuya. Decide qué cargas aceptas.': 'Someone will claim a debt that is not yours. Decide which burdens you accept.',
    'Una alianza se romperá cuando dejes de pagar por la paz.': 'An alliance will break when you stop paying for peace.',
    'El poder se acercará con una oferta. Examina lo que exige a cambio.': 'Power will approach with an offer. Examine what it demands in return.',
    'Lo que olvidaste no desapareció. Hoy reconocerás su contorno.': 'What you forgot has not vanished. Today you will recognize its outline.',
    'Un detalle mínimo abrirá una puerta que creías cerrada.': 'A tiny detail will open a door you thought was shut.',
    'No recordarás el rostro. Recordarás lo que sentiste al verlo.': 'You will not remember the face. You will remember how it made you feel.',
    'Llegará una ayuda inesperada. Escucha lo que pide a cambio.': 'Unexpected help will arrive. Listen to what it asks in return.',
    'Un aviso llegará tarde. Aún tendrás tiempo de elegir.': 'A warning will arrive late. You will still have time to choose.',
    'Te echarán un cable por última vez. Descubrirás que ya sabes continuar.': 'Someone will help you one last time. You will discover you already know how to go on.',
    'Un nombre antiguo dejará de servirte. El siguiente aún está por escribirse.': 'An old name will no longer fit. The next has yet to be written.',
    'No confundas desaparecer con empezar de nuevo.': 'Do not mistake disappearing for starting over.',
    'El espejo devolverá un rostro sin nombre. Tú decidirás qué hacer con él.': 'The mirror will return a nameless face. You will decide what to do with it.',
    'Elige una carta. Nadie conoce el orden de esta tirada.': 'Choose a card. No one knows the order of this draw.',
    'FIN DE LOS TIEMPOS': 'END OF TIMES',
    'MEZCLAR DE NUEVO': 'SHUFFLE AGAIN',
    'COPIAR ENLACE': 'COPY LINK',
    'ENLACE COPIADO': 'LINK COPIED',
    'NO SE PUDO COPIAR': 'COULD NOT COPY',
    'Revelar carta ': 'Reveal card ',
    'Carta ': 'Card ',
    'CARTA ': 'CARD ',
    'PREDICCIÓN': 'PREDICTION',
    'Retrato de ': 'Portrait of ',
    'Fragmentos del registro': 'Record fragments',
    'SIN ACCESO': 'LOCKED',
    'REGISTRO ': 'RECORD ',
    'INFORME': 'REPORT',
    'RESULTADO DEL ANÁLISIS': 'ANALYSIS RESULT',
    'ABRIR REGISTRO 002': 'OPEN RECORD 002',
    'ABRIR SIGUIENTE FRAGMENTO': 'OPEN NEXT FRAGMENT',
    'NINGUNA': 'NONE',
    'EXPEDIENTE / INDEPENDIENTE': 'CASE FILE / INDEPENDENT',
    'CARGOS': 'CHARGES',
    'ASESINATO · VIOLACIÓN · EXTORSIÓN · ROBO': 'MURDER · RAPE · EXTORTION · THEFT',
    'RELACIÓN CON EL HERALDO': 'RELATION TO THE HERALD',
    'IDENTIDAD / DESCONOCIDA': 'IDENTITY / UNKNOWN',
    'IDENTIDAD / ENMASCARADA': 'IDENTITY / MASKED',
    'IDENTIDAD / EN FORMACIÓN': 'IDENTITY / EMERGING',
    'SUJETO / PROYECTO HERALDO': 'SUBJECT / PROJECT HERALD',
    'MEMORIA BORRADA': 'MEMORY ERASED',
    'INTENTAR RECORDAR': 'TRY TO REMEMBER',
    'ARCHIVO / IMAGEN NO DISPONIBLE': 'ARCHIVE / IMAGE UNAVAILABLE',
    'Tyler no recuerda su nombre. Pero ella sí recuerda el suyo.': 'Tyler cannot remember her name. But she remembers his.',
    'ROSTRO NO RECUPERADO': 'FACE NOT RECOVERED',
    'INTENTO ': 'ATTEMPT ',
    'Retrato de Tyler antes de la máscara, con el rostro en sombra y una conexión en la nuca': 'Portrait of Tyler before the mask, his face in shadow and a connection at the back of his neck',
    'Retrato de Inteligencia, un hombre francés con gafas de sol oscuras': 'Portrait of Intelligence, a French man wearing dark sunglasses',
    'Retrato de cintura hacia arriba del jefe de la tríada, con camiseta de tirantes, cadenas y tatuajes en cuello y brazos': 'Waist-up portrait of the triad boss, wearing a tank top and chains, with tattoos on his neck and arms',
    'Silueta de una mujer de identidad desconocida; el rostro permanece oculto': 'Silhouette of an unidentified woman; her face remains hidden',
    'Retrato robot de ': 'Composite portrait of ',
    ', con parche en un ojo': ', wearing an eye patch',
    ', representada como una silueta sin rasgos visibles': ', depicted as a faceless silhouette',
    'El Heraldo medita ante reflejos que se oscurecen; solo él sostiene una esfera': 'The Herald meditates before fading reflections; only he holds a sphere',
    'ESPEJOS / REPETICIÓN / SILENCIO': 'MIRRORS / REPETITION / SILENCE',
    'ENTRAR EN MEDITACIÓN': 'ENTER MEDITATION',
    'VOLVER A LA SUPERFICIE': 'RETURN TO THE SURFACE',
    'Los reflejos se apagan. La esfera permanece.': 'The reflections fade. The sphere remains.',
    'FICHA 0': 'DOSSIER 0',
    'FICHA ': 'DOSSIER ',
    'CONFIDENCIAL': 'CONFIDENTIAL',
    'PACIENTE': 'PATIENT',
    'IDENTIDAD RESERVADA': 'IDENTITY WITHHELD',
}

spanish_source = source
for original, english in sorted(translations.items(), key=lambda item: len(item[0]), reverse=True):
    if original not in spanish_source:
        raise ValueError(f"Missing Spanish text: {original!r}")
    source = source.replace(original, english)

source = source.replace('data-language="es" href="./" aria-current="page"', 'data-language="es" href="./"')
source = source.replace('data-language="en" href="en.html"', 'data-language="en" href="en.html" aria-current="page"')
(ROOT / "en.html").write_text(source)
